POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "092ce768-68e5-448f-8747-b0b149b01131",
  "account_id_to": "9a9d550f-c475-4bad-a034-cfd3dbdb6813",
  "amount": 200
}

###
GET http://localhost:3003/balances/092ce768-68e5-448f-8747-b0b149b01131
Accept: application/json

###
GET http://localhost:3003/balances/9a9d550f-c475-4bad-a034-cfd3dbdb6813
Accept: application/json

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "9a9d550f-c475-4bad-a034-cfd3dbdb6813",
    "account_id_to": "092ce768-68e5-448f-8747-b0b149b01131",
    "amount": 100
}

